application: omeglepro
version: omeagull
runtime: python27
api_version: 1
threadsafe: true

default_expiration: 24h

handlers:

- url: /lib
  static_dir: lib

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  expiration: 1827d

- url: /(.*\.(css|json|png))
  static_files: static/\1
  upload: static/(.*\.(css|ico|json|png))

- url: /(.*\.js)
  static_files: \1
  upload: (.*\.js)

- url: /(captchaChallenge|captchaImage)/(.*)
  script: app.app

- url: /(.*)
  static_files: index.html
  upload: index.html
